services:
  postgres:
    image: postgres:17.6
    command:
      - postgres
      - '-c'
      - wal_level=logical
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VerySecure
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack-server:latest
    environment:
      - REDIS_ARGS="--requirepass VerySecure"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  byteserve:
    image: ghcr.io/ipmake/byteserve:latest
    restart: on-failure:5
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:VerySecure@postgres:5432/postgres
      - REDIS_URL=redis://default:VerySecure@redis:6379
    volumes:
      - ./data/storage:/app/storage
      - /tmp/byteserve_temp:/app/storage/.temp
      - byteserve_config:/app/data

volumes:
  postgres_data:
  byteserve_config: