services:
  postgres:
    image: postgres:17.6
    command:
      - postgres
      - '-c'
      - wal_level=logical
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VerySecure
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack-server:latest
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]

  byteserve:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:VerySecure@postgres:5432/postgres
      - REDIS_CONNECTION_STRING=redis://redis:6379
    volumes:
      - ./data/storage:/app/storage
      - byteserve_config:/app/data


volumes:
  postgres_data:
  byteserve_config: